### ISSUE TITLE
Legacy API ?

### ISSUE THREAD

**Issue by johndodev** [boxtal/php-library#6]
Hello,

have there been any changes today ? 

I work on a platform who use for examples https://api.boxtal.com/legacy/check-api-key, and this is not working anymore.

I tryed to install this library in my project but it seems it's seems this library is only working as standalone.

I dont find any real endpoint documentation or SDK. 

Is there someone (a real developper team) still working on this API or a proper PHP SDK ?

**Comment by Arnaud-DT** [comment]
Hi,
Sorry for the long due answer... Indeed the v1 API and library are only maintained to support our legacy WooCommerce and Prestashop plugins. Please check our latest documentation on https://developer.boxtal.com, on which we will launch our v3 API in a few weeks. There is no plan however for a PHP library for the v3 API currently.
